name: Playwright Tests
on:
  push:
    branches: [develop]
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      domain:
        default: https://www.tfl.gov.uk/
        description: Domain endpoint to run tests against
        required: true
        type: string

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 🏗️
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache playwright binaries
        uses: actions/cache@v3.2.3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: cache-playwright-linux-1.19.2

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
