name: Playwright Tests
on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      domain:
        default: https://tfl.gov.uk
        description: Domain endpoint to run tests against
        required: false
        type: string

jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test chromium src/tests/tfl.spec.ts

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retentions-days: 7
